export const topics: string[] = [
  // Medical & Health Sciences
  'Medicine',
  'Dentistry',
  'Pharmacy',
  'Nursing',
  'Midwifery',
  'Physiotherapy',
  'Occupational Therapy',
  'Radiology',
  'Medical Laboratory Sciences',
  'Nutrition and Dietetics',
  'Public Health',
  'Epidemiology',
  'Biomedical Engineering',
  'Neuroscience',
  'Anatomy',
  'Physiology',
  'Pathology',
  'Immunology',
  'Genetics',
  'Parasitology',
  'Veterinary Medicine',
  'Toxicology',
  'Oncology',
  'Cardiology',
  'Dermatology',
  'Surgery',
  'Ophthalmology',
  'Psychiatry',
  'Anesthesiology',

  // Science & Natural Sciences
  'Biology',
  'Microbiology',
  'Molecular Biology',
  'Biotechnology',
  'Chemistry',
  'Biochemistry',
  'Physics',
  'Astrophysics',
  'Environmental Science',
  'Earth Science',
  'Geology',
  'Geography',
  'Meteorology',
  'Oceanography',
  'Mathematics',
  'Applied Mathematics',
  'Statistics',
  'Data Science',
  'Zoology',
  'Botany',
  'Ecology',
  'Marine Biology',
  'Environmental Chemistry',
  'Hydrology',

  // Engineering & Technology
  'Mechanical Engineering',
  'Electrical Engineering',
  'Electronics Engineering',
  'Computer Engineering',
  'Software Engineering',
  'Civil Engineering',
  'Architecture',
  'Structural Engineering',
  'Industrial Engineering',
  'Chemical Engineering',
  'Petroleum Engineering',
  'Mining Engineering',
  'Aerospace Engineering',
  'Mechatronics Engineering',
  'Robotics Engineering',
  'Environmental Engineering',
  'Marine Engineering',
  'Automotive Engineering',
  'Textile Engineering',
  'Materials Engineering',
  'Nuclear Engineering',
  'Telecommunications Engineering',
  'Systems Engineering',
  'Energy Engineering',

  // Computer & IT
  'Computer Science',
  'Information Technology',
  'Information Systems',
  'Cybersecurity',
  'Artificial Intelligence',
  'Machine Learning',
  'Data Engineering',
  'Cloud Computing',
  'Web Development',
  'Mobile Application Development',
  'Game Development',
  'Network Engineering',
  'Blockchain Technology',
  'Human–Computer Interaction',
  'Computer Graphics',
  'Software Architecture',
  'Database Management',

  // Business, Management & Economics
  'Business Administration',
  'Management',
  'Marketing',
  'Finance',
  'Accounting',
  'Banking',
  'Economics',
  'International Business',
  'Entrepreneurship',
  'Supply Chain Management',
  'Logistics',
  'E-commerce',
  'Human Resource Management',
  'Project Management',
  'Real Estate',
  'Insurance',
  'Hospitality Management',
  'Tourism Management',
  'Investment Management',
  'Business Analytics',

  // Social Sciences
  'Sociology',
  'Psychology',
  'Political Science',
  'International Relations',
  'Anthropology',
  'Criminology',
  'Social Work',
  'Public Administration',
  'Education',
  'Gender Studies',
  'Development Studies',
  'Communication Studies',

  // Humanities
  'Philosophy',
  'History',
  'Literature',
  'Linguistics',
  'Languages',
  'Translation and Interpretation',
  'Theology',
  'Cultural Studies',
  'Archeology',
  'Religious Studies',
  'Ethics',
  'Classical Studies',

  // Art, Design & Media
  'Fine Arts',
  'Graphic Design',
  'Interior Design',
  'Industrial Design',
  'Fashion Design',
  'Architecture',
  'Photography',
  'Film Studies',
  'Cinematography',
  'Music',
  'Performing Arts',
  'Theater',
  'Animation',
  'Visual Communication',
  'Media Studies',
  'Journalism',
  'Advertising',
  'Digital Media',
  'Game Design',
  'Creative Writing',
  'Art History',

  // Law & Legal Studies
  'Law',
  'International Law',
  'Criminal Law',
  'Civil Law',
  'Corporate Law',
  'Human Rights Law',
  'Environmental Law',
  'Intellectual Property Law',
  'Commercial Law',
  'Tax Law',
  'Family Law',
  'Constitutional Law',

  // Agriculture & Environmental Fields
  'Agriculture',
  'Agronomy',
  'Horticulture',
  'Plant Protection',
  'Animal Science',
  'Food Science and Technology',
  'Forestry',
  'Fisheries',
  'Environmental Management',
  'Sustainable Development',
  'Soil Science',
  'Agroecology',

  // Paramedical & Allied Health Fields
  'Emergency Medicine',
  'Medical Imaging',
  'Dental Hygiene',
  'Optometry',
  'Speech Therapy',
  'Audiology',
  'Orthoptics',
  'Rehabilitation Sciences',
  'Health Informatics',

  // Applied & Professional Fields
  'Aviation',
  'Maritime Studies',
  'Logistics and Transportation',
  'Military Science',
  'Fire Safety Engineering',
  'Urban Planning',
  'Public Safety',
  'Security Studies',
  'Sports Science',
  'Physical Education',
]

export const universities: string[] = [
  'Hamedan University of Technology',
  'Hekmat Private University',
  'Abadan University of Medical Sciences',
  'Al-Mustafa International University',
  'Alzahra University',
  'Amirkabir University of Technology (Tehran Polytechnic)',
  'Khatam university',
  'Ahvaz Jundishapur University of Medical Sciences',
  'Ayatollah Borujerdi University',
  'Comprehensive University of Technology, Tehran',
  'Damghan University',
  'Danesh Alborz University, Qazvin',
  'Hatef Higher Education Institute, Zahedan',
  'Faran Virtual University, Tehran',
  'Parsian Virtual University, Tehran',
  'Lamei Gorgani Institute of Higher Education',
  'Farabi Institute of Virtual Higher Education',
  'Farhangian University',
  'Fasa University',
  'Fasa University of Medical Sciences, Fasa',
  'Fatemiye University of Medical Sciences, Qom',
  'Ferdowsi University of Mashhad, Mashhad',
  'Mohajer Technical University of Isfahan, Isfahan',
  'Garmsar University',
  'Gilan University of Medical Sciences',
  'Golestan University, Gorgan',
  'Golestan University of Medical Sciences, Gorgan',
  'Golpayegan University of Engineering, Golpayegan',
  'Gonabad University of Medical Sciences, Gonabad',
  'Tabari Institute of Higher Education',
  'Gonbad Kavous University, Golestan',
  'Gorgan University of Agricultural Sciences and Natural Resources, Gorgan',
  'Gorgan University of Medical Sciences',
  'Hadith Science College, Tehran',
  'Hamedan University of Medical Sciences',
  'Hormozgan University, Bandar Abbas',
  'Hormozgan University of Medical Sciences, Bandar Abbas',
  'Ilam University, Ilam',
  'Medical University of Ilam, Ilam',
  'Information and Communication Technology Faculty, Tehran',
  'Industrial Management Institute, main campus Tehran, central campus Isfahan',
  'Institute for Advanced Studies in Basic Sciences (IASBS), Zanjan',
  'Institute for Higher Education ACECR Khouzestan, Ahvaz',
  'Institute for Studies in Theoretical Physics and Mathematics (IPM)',
  'International Institute of Earthquake Engineering and Seismology',
  'International University of Chabahar',
  'International University of Iran, Washington D.C.',
  'Iran Informatic Institute (U.A.S.T., Tehran)',
  'Iran Polymer and Petrochemical Institute',
  'Iran University of Medical Sciences',
  'Iran University of Science and Technology (IUST)',
  'University of Science and Culture',
  'Iraniyan Internet University (Tehran)',
  'Iranian Space Research Center',
  'Isfahan University of Medical Sciences',
  'Isfahan University of Technology',
  'Islamic Azad University',
  'Islamic Azad University, Abhar',
  'Islamic Azad University, Ahar Branch',
  'Islamic Azad University, Ahvaz Branch',
  'Islamic Azad University, Aliabad Katul',
  'Islamic Azad University, Arak Branch',
  'Islamic Azad University, Astara Branch',
  'Islamic Azad University, Baft',
  'Islamic Azad University, Bandar Abbas',
  'Islamic Azad University, Bojnourd Branch',
  'Islamic Azad University, Bonab',
  'Islamic Azad University, Bushehr',
  'Islamic Azad University, Central Tehran Branch',
  'Islamic Azad University, Damavand Branch',
  'Islamic Azad University, Darab Branch',
  'Islamic Azad University, Dezful Branch',
  'Islamic Azad University, Eghlid Branch',
  'Islamic Azad University, Estahban Branch',
  'Islamic Azad University, Falavarjan Branch',
  'Islamic Azad University, Farahan Branch',
  'Islamic Azad University, Science and Research Branch, Fars',
  'Islamic Azad University, Ferdows Branch',
  'Islamic Azad University, Firuzabad Branch',
  'Islamic Azad University, Gachsaran Branch',
  'Islamic Azad University, Garmsar Branch',
  'Islamic Azad University, Gonabad Branch',
  'Islamic Azad University, Hamedan Branch',
  'Islamic Azad University, Islamshahr Branch',
  'Islamic Azad University, Karaj Branch',
  'Islamic Azad University, Kazeroon Branch',
  'Islamic Azad University, Kerman Branch',
  'Islamic Azad University, Kermanshah Branch',
  'Islamic Azad University, Khomain Branch',
  'Islamic Azad University, Khomeyni Shahr Branch',
  'Islamic Azad University, Isfahan (Khorasgan) Branch',
  'Islamic Azad University, Khoy Branch',
  'Islamic Azad University, Larestan Branch',
  'Islamic Azad University, Mahabad Branch',
  'Islamic Azad University, Majlesi Branch',
  'Islamic Azad University, Maku Branch',
  'Islamic Azad University, Maragheh Branch',
  'Islamic Azad University, Marvdasht Branch',
  'Islamic Azad University, Maybod Branch',
  'Islamic Azad University, Miyaneh Branch',
  'Islamic Azad University, Naein Branch',
  'Islamic Azad University, Nishabur Branch',
  'Islamic Azad University, Noor Branch',
  'Islamic Azad University, Gorgan Branch',
  'Islamic Azad University, Mashhad Branch',
  'Islamic Azad University, Masjed Soleyman Branch',
  'Islamic Azad University, Najafabad Branch',
  'Islamic Azad University, Neyriz Branch',
  'Islamic Azad University, Shahinshahr Branch',
  'Islamic Azad University, Parand Branch',
  'Qazvin Islamic Azad University',
  'Islamic Azad University, Shahr-e-Qods Branch',
  'Islamic Azad University, Qom Branch',
  'Islamic Azad University, Quchan Branch',
  'Islamic Azad University, Region One',
  'Islamic Azad University Roudehen Branch',
  'Islamic Azad University, Sabzevar Branch',
  'Islamic Azad University, Sanandaj Branch',
  'Islamic Azad University, Sari Branch',
  'Islamic Azad University, Saveh Branch',
  'Islamic Azad University, Science and Research Branch, Tehran (Tehran)',
  'Islamic Azad University, West Tehran Branch',
  'Islamic Azad University, Sepidan Branch',
  'Islamic Azad University, Shabestar Branch',
  'Islamic Azad University, Shahr-e-Rey Branch',
  'Islamic Azad University, Shahrekord Branch',
  'Islamic Azad University, Shahreza Branch',
  'Islamic Azad University, Shahrood Branch',
  'Islamic Azad University, Shiraz Branch',
  'Islamic Azad University, Shirvan Branch',
  'Islamic Azad University, Shoushtar Branch',
  'Islamic Azad University, Sirjan Branch',
  'Islamic Azad University, Tabriz Branch',
  'Islamic Azad University, Tafresh Branch',
  'Islamic Azad University, Takistan Branch',
  'Islamic Azad University, East Tehran Branch',
  'Islamic Azad University, Tehran Medical Branch',
  'Islamic Azad University, North Tehran Branch',
  'Islamic Azad University, South Tehran Branch',
  'Islamic Azad University, Urmia Branch',
  'Islamic Azad University, Varamin Branch',
  'Islamic Azad University, Yasuj Branch',
  'Islamic Azad University, Yazd Branch',
  'Islamic Azad University, Zahedan Branch',
  'Islamic Azad University, Zanjan Branch',
  'Islamic Azad University, Zarand Branch',
  'Jahad Daneshgahi Academic Institute of Ahvaz',
  'Jahrom University of Medical Sciences, Jahrom',
  'Jami Institute of Technology, Isfahan',
  'Kar Higher Education Institute, Qazvin',
  'K.N. Toosi University of Technology',
  'Kashan University of Medical Sciences',
  'Kerman Khaje-Nasir Higher Education Center (K.K.H.E.C.), Kerman',
  'Kerman University of Medical Sciences',
  'Kermanshah University of Medical Sciences',
  'Kermanshah University of Technology, Kermanshah',
  'Kharazmi University',
  'Khayyam Institute of Higher Education, Mashhad',
  'Khorasan Institute of Higher Education, Mashhad',
  'Khorramshahr University of Nautical Sciences and Technologies, Khorramshahr',
  'Kish University (Kish Higher Education Institute)',
  'Kordestan University of Medical Sciences, Sanandaj',
  'Kowsar Institute of Higher Education / Kowsar Ghazvin Non-Profit Institute of Higher Education, Ghazvin',
  'Lorestan University, Khorramabad',
  'Lorestan University of Medical Sciences, Khorramabad',
  'Malek-Ashtar University of Technology',
  'Mashhad University of Medical Sciences',
  'Mazandaran University of Medical Sciences, Sari',
  'Mazandaran University of Science and Technology',
  "Medical University for the Islamic Republic of Iran's Army, Tehran",
  'Meybod University',
  'Mofid University',
  'Mohaghegh Ardabili University',
  'Montazeri Technical College of Mashhad',
  'NAJA University of Police, Tehran',
  'Nooretouba Virtual University, Tehran',
  'Payame Noor University of Mashhad',
  'Payame Noor University of Karaj',
  'Payame Noor University of Eshtehard',
  'Payame Noor University, Shiraz',
  'Payame Noor University, Tabriz',
  'Payame Noor University, Tehran',
  'Payame Noor University, Urmia',
  'Persian Gulf University',
  'Petroleum University of Technology',
  'Power and Water University of Technology, Tehran',
  'Qazvin University of Medical Sciences',
  'Qeshm Institute of Higher Education',
  "Qom Boy's Technical College",
  'Qom University of Medical Sciences, Qom',
  'Rafsanjan University of Medical Sciences',
  'Raja University, Qazvin',
  'Razi University',
  'The Research Institute of Hawzeh va Daneshgah',
  'Sabzevar School of Medical Sciences, Sabzevar',
  'Sadjad Institute of Higher Education, Mashhad',
  'Safir Danesh University of Ilam',
  'Sarab University of Medical Sciences',
  'Sari Agricultural Sciences and Natural Resources University',
  'Salman Farsi University of Kazerun',
  'Sahand University of Technology',
  'School of International Relations (SIR), Tehran',
  'Semnan University',
  'Semnan University of Medical Sciences, Semnan',
  'Shahab Danesh University',
  'Shahed University, Tehran',
  'Shahed University of Medical Sciences, Tehran',
  'Shahid Bahonar University of Kerman',
  'Shahid Beheshti Teacher Training College',
  'Shahid Beheshti University, Tehran',
  'Shahid Beheshti University of Medical Sciences',
  'Shahid Chamran University North Branch of Dezful',
  'Shahid Chamran University of Ahvaz',
  'Shahid Rajaee Teacher Training University, Tehran',
  'Shahid Sadoughi University of Medical Sciences and Health Services',
  'Shahid Sattari University of Aeronautical Engineering, Tehran',
  'Shahid Shamsipour Institute of Technology',
  'Shahrekord University',
  'Shahrekord University of Medical Sciences',
  'Shahrood University of Technology',
  'Shahroud University of Medical Sciences',
  'Shariaty Technical College, Tehran',
  'Sharif University of Technology, Tehran',
  'Sharif University of Technology, International Campus – Kish',
  'Sheikhbahaee institute of higher education, Isfahan',
  'Shiraz University',
  'Shiraz University of Medical Sciences',
  'Shiraz University of Technology',
  'Shomal University',
  'Soore University',
  'Taali Institute of HigherEducation, Qom',
  'Tabarestan University (Tabarestan Higher Education Institution)',
  'Tabriz Islamic Art University, Tabriz',
  'Tabriz University of Medical Sciences',
  'Tafresh University, Tafresh',
  'Tarbiat Moallem University (of Arak)',
  'Tarbiat Moallem University of Sabzevar, Sabzevar',
  'Tarbiat Modares University (Professor Training University)',
  'Tehran University of Medical Sciences',
  'Technical and Vocational University',
  'Tehran University of Medical Sciences – International Campus (TUMS-IC)',
  'Torbat Heydarieh University of Medical Sciences',
  'University College of Nabi Akram, Tabriz',
  'University of Applied Science and Technology',
  'University of Arak',
  'University of Birjand, Birjand',
  'University of Bonab',
  'University of Defence Sciences and Technologies, Isfahan',
  'University of Economic sciences, Tehran',
  'University of Guilan',
  'University of Isfahan',
  'University of Islamic Sects, Tehran',
  'University of Judicial Sciences and Administrative Services, Tehran',
  'University of Kashan, Kashan',
  'University of Kordestan',
  'University of Mazandaran',
  'University of Qom',
  'University of Sistan and Baluchestan',
  'University of Social Welfare and Rehabilitation Sciences, Tehran',
  'University of Tabriz, Tabriz',
  'University of Tehran, Tehran',
  'University of Zabol, Zabol',
  'University of Yazd',
  'University of Zanjan',
  'Urmia University',
  'Urmia University of Medical Sciences',
  'Urmia University of Technology',
  'ValiAsr University of Rafsanjan (Vali-E-Asr), Rafsanjan',
  'Yasuj University, Yasuj',
  'Yasuj University of Medical Sciences',
  'Yazd Institute of Higher Education, ACECR',
  'Isfahan Institute of Higher Education, ACECR',
  'Zabol University of Medical Sciences',
  'Zabol University',
  'Zahedan University of Medical Sciences, Zahedan',
  'Zanjan University of Medical Sciences, Zanjan',
  'Velayat University, in Iranshahr',
]
